#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  adv-commercialpaper-net:
    external:
      name: adv-commercialpaper-net

volumes:
  peer1.magnetocorp.example.com:

  ca.magnetocorp.example.com:
    container_name: camagnetocorp
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=camagnetocorp
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.magnetocorp.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1e83a8ac1ec5e2d0e8444286e18f7ecb757c328f1420bfa8e5daaa67a02033ca_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/magnetocorp.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - commercialpaper-net
