#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  adv-commercialpaper-net:
    external:
      name: adv-commercialpaper-net

services:
  ca.magnetocorp.example.com:
    container_name: camagnetocorp
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=camagnetocorp
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /var/hyperledger/identity/ca/ca.magnetocorp.example.com/ca.magnetocorp.example.com-cert.pem --ca.keyfile /var/hyperledger/identity/ca/ca.magnetocorp.example.com/906189e49cac840377c5aa3ebf27c6a870375df577b54c70fa9b08a1d4958a22_sk -b admin:adminpw -d'
    volumes:
      - ./../../../identity/:/var/hyperledger/identity
    networks:
      - adv-commercialpaper-net
